[custom.all.idris2-brainfuck-array]
type = "local"
path = "."
ipkg = "idris2-brainfuck-array.ipkg"
test = "test/test.ipkg"

[custom.all.idris2-brainfuck-array-test]
type = "local"
path = "test"
ipkg = "test.ipkg"
